package c2item

import (
	"github.com/BismarckDD/Caocao/c2core/c2status"
	"github.com/BismarckDD/Caocao/c2core/c2unit_category"
)

// Save file will save this
var ItemWareHouse = []Item{
	// 以下为普通物品
	{
		Id:             0,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "短剑",
		BaseAttack:     10,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForSword,
	},
	{
		Id:             1,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "大剑",
		BaseAttack:     40,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForSword,
	},
	{
		Id:             2,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "钢剑",
		BaseAttack:     80,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForSword,
	},
	{
		Id:             3,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "短枪",
		BaseAttack:     10,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForLance,
	},
	{
		Id:             4,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "长枪",
		BaseAttack:     40,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForLance,
	},
	{
		Id:             5,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "钢枪",
		BaseAttack:     80,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForLance,
	},
	{
		Id:             6,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "短弓",
		BaseAttack:     10,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForBow,
	},
	{
		Id:             7,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "大弓",
		BaseAttack:     40,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForBow,
	},
	{
		Id:             8,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "铁弓",
		BaseAttack:     80,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForBow,
	},
	{
		Id:             9,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "木棍",
		BaseAttack:     10,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForClub,
	},
	{
		Id:             10,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "铜棍",
		BaseAttack:     40,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForClub,
	},
	{
		Id:             11,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "铁棍",
		BaseAttack:     80,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForClub,
	},
	{
		Id:             12,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "木质投石机",
		BaseAttack:     10,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryPaoChe,
	},
	{
		Id:             13,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "铜质投石机",
		BaseAttack:     40,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryPaoChe,
	},
	{
		Id:             14,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "铁制投石机",
		BaseAttack:     80,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryPaoChe,
	},
	{
		Id:             15,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "竹扇",
		BaseSpirit:     10,
		UpSpirit:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForMagicFan,
	},
	{
		Id:             16,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "军扇",
		BaseSpirit:     40,
		UpSpirit:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForMagicFan,
	},
	{
		Id:             17,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "铁扇",
		BaseSpirit:     80,
		UpSpirit:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForMagicFan,
	},
	{
		Id:             18,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "石制宝剑",
		BaseSpirit:     10,
		UpSpirit:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForMagicSword,
	},
	{
		Id:             19,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "铜制宝剑",
		BaseSpirit:     40,
		UpSpirit:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForMagicSword,
	},
	{
		Id:             20,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "铁制宝剑",
		BaseSpirit:     80,
		UpSpirit:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForMagicSword,
	},
	{
		Id:             21,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "皮铠",
		BaseDefence:    10,
		UpDefence:      10,
		UnitCategoryId: c2unit_category.UnitCategoryForArmor,
	},
	{
		Id:             22,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "铜铠",
		BaseDefence:    40,
		UpDefence:      10,
		UnitCategoryId: c2unit_category.UnitCategoryForArmor,
	},
	{
		Id:             23,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "铁铠",
		BaseDefence:    80,
		UpDefence:      10,
		UnitCategoryId: c2unit_category.UnitCategoryForArmor,
	},
	{
		Id:             24,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "布衣",
		BaseDefence:    10,
		UpDefence:      10,
		UnitCategoryId: c2unit_category.UnitCategoryForCloth,
	},
	{
		Id:             25,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "皮衣",
		BaseDefence:    40,
		UpDefence:      10,
		UnitCategoryId: c2unit_category.UnitCategoryForCloth,
	},
	{
		Id:             26,
		Level:          1,
		MaxLevel:       3,
		Exp:            0,
		Name:           "战斗服",
		BaseDefence:    80,
		UpDefence:      10,
		UnitCategoryId: c2unit_category.UnitCategoryForCloth,
	},
	// 以下为宝物：赤兔马、的卢、龙鳞铠
	{
		Id:             128,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "雌雄双剑",
		BaseAttack:     10,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForSword,
	},
	{
		Id:             129,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "青钢剑",
		BaseAttack:     10,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForSword,
	},
	{
		Id:             130,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "倚天剑",
		BaseAttack:     10,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForSword,
	},
	{
		Id:             131,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "古锭刀",
		BaseAttack:     10,
		UpAttack:       10,
		BaseExplosive:  10,
		UnitCategoryId: c2unit_category.UnitCategoryForSword,
	},
	{
		Id:             132,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "青龙偃月刀",
		BaseAttack:     10,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForLance,
		StrikeAssist:   c2status.StrikeAssistForbiddenCS,
	},
	{
		Id:             133,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "丈八蛇矛",
		BaseAttack:     80,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForLance,
		StrikeAssist:   c2status.StrikeAssistEnablePS,
	},
	{
		Id:             134,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "方天画戟",
		BaseAttack:     10,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForLance,
		StrikeAssist:   c2status.StrikeAssistEnableLS,
	},
	{
		Id:             135,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "吕布之弓",
		BaseAttack:     10,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForBow,
		StrikeAssist:   c2status.StrikeAssistWithHold,
	},
	{
		Id:             136,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "李广之弓",
		BaseAttack:     10,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForBow,
		StrikeAssist:   c2status.StrikeAssistWithProhibition,
	},
	{
		Id:             137,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "流星锤",
		BaseAttack:     10,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForClub,
		StrikeAssist:   c2status.StrikeAssistWithChaos,
	},
	{
		Id:             138,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "双鞭",
		BaseAttack:     10,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForClub,
		StrikeAssist:   c2status.StrikeAssistEnableCCS,
	},
	{
		Id:             139,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "金火罐跑",
		BaseAttack:     10,
		UpAttack:       10,
		UnitCategoryId: c2unit_category.UnitCategoryPaoChe,
		StrikeAssist:   c2status.StrikeAssistWithToxic,
	},
	{
		Id:             140,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "芭蕉扇",
		BaseSpirit:     10,
		UpSpirit:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForMagicFan,
		SpellAssist:    c2status.SpellAssistWindEnhance,
	},
	{
		Id:             141,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "五火神焰扇",
		BaseSpirit:     10,
		UpSpirit:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForMagicFan,
		SpellAssist:    c2status.SpellAssistFireEnhance,
	},
	{
		Id:             142,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "白羽扇",
		BaseSpirit:     10,
		UpSpirit:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForMagicFan,
		SpellAssist:    c2status.SpellAssistMPReduce,
	},
	{
		Id:                 143,
		Level:              1,
		MaxLevel:           9,
		Exp:                0,
		Name:               "七星剑",
		BaseSpirit:         10,
		UpSpirit:           10,
		UnitCategoryId:     c2unit_category.UnitCategoryForMagicSword,
		BaseMagicHitChance: 15,
	},
	{
		Id:             144,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "圣者宝剑",
		BaseSpirit:     10,
		UpSpirit:       10,
		UnitCategoryId: c2unit_category.UnitCategoryForMagicSword,
		BaseHPInc:      20,
	},
	{
		Id:                    145,
		Level:                 1,
		MaxLevel:              9,
		Exp:                   0,
		Name:                  "镜铠",
		BaseDefence:           10,
		UpDefence:             10,
		UnitCategoryId:        c2unit_category.UnitCategoryForArmor,
		BaseRemoteDodgeChance: 100,
	},
	{
		Id:                      146,
		Level:                   1,
		MaxLevel:                9,
		Exp:                     0,
		Name:                    "黄金铠",
		BaseDefence:             10,
		UpDefence:               10,
		UnitCategoryId:          c2unit_category.UnitCategoryForArmor,
		BaseCriticalDodgeChance: 100,
	},
	{
		Id:                     147,
		Level:                  1,
		MaxLevel:               9,
		Exp:                    0,
		Name:                   "连环铠",
		BaseDefence:            10,
		UpDefence:              10,
		UnitCategoryId:         c2unit_category.UnitCategoryForArmor,
		BaseDoubleStrikeChance: 100, // 这里改为主动双击
	},
	{
		Id:                         148,
		Level:                      1,
		MaxLevel:                   9,
		Exp:                        0,
		Name:                       "白银铠",
		BaseDefence:                10,
		UpDefence:                  10,
		UnitCategoryId:             c2unit_category.UnitCategoryForArmor,
		BaseMagicDamageReduceRatio: 50,
	},
	{
		Id:             149,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "龙鳞铠",
		BaseDefence:    10,
		UpDefence:      10,
		UnitCategoryId: c2unit_category.UnitCategoryForArmor,
		// MagicDefense:   true,
	},
	{
		Id:             150,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "飞龙道袍",
		BaseDefence:    10,
		UpDefence:      10,
		UnitCategoryId: c2unit_category.UnitCategoryForCloth,
		BaseExplosive:  10,
		UpExplosive:    10, // 这里每升一级 爆发力+10
	},
	{
		Id:             151,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "鹤氅",
		BaseDefence:    10,
		UpDefence:      10,
		UnitCategoryId: c2unit_category.UnitCategoryForCloth,
		BaseSpirit:     10, // 一级辅助精神力+10
		UpSpirit:       10, // 每升一级，辅助精神力+10
	},
	{
		Id:             152,
		Level:          1,
		MaxLevel:       9,
		Exp:            0,
		Name:           "漆黑道服",
		BaseDefence:    10,
		UpDefence:      10,
		UnitCategoryId: c2unit_category.UnitCategoryForCloth,
		BaseMPInc:      10,
		UpMPInc:        10,
	},
	{
		Id:                 153,
		Level:              1,
		MaxLevel:           9,
		Exp:                0,
		Name:               "凤凰羽衣",
		BaseDefence:        10,
		UpDefence:          10,
		UnitCategoryId:     c2unit_category.UnitCategoryForCloth,
		BaseHPRecoverRatio: 4, // 一级时生命恢复4%
		UpHPRecoverRatio:   3, // 这里每升一级，生命恢复+3%
	},
	{
		Id:                   154,
		Level:                1,
		MaxLevel:             0,
		Exp:                  0,
		Name:                 "白银盾",
		UnitCategoryId:       c2unit_category.UnitCategoryWuJiang,
		BaseMagicDodgeChance: 15,
	},
	{
		Id:                   155,
		Level:                1,
		MaxLevel:             0,
		Exp:                  0,
		Name:                 "风神盾",
		UnitCategoryId:       c2unit_category.UnitCategoryQunXiong, // 只有君主能装备？
		BaseDodgeChance:      15,
		BaseMagicDodgeChance: 15,
	},
	{
		Id:             156,
		Level:          1,
		MaxLevel:       0,
		Exp:            0,
		Name:           "风车轮",
		UnitCategoryId: c2unit_category.UnitCategoryPaoChe,
		Move:           2,
	},
	{
		Id:             157,
		Level:          1,
		MaxLevel:       0,
		Exp:            0,
		Name:           "爪黄飞电",
		UnitCategoryId: c2unit_category.UnitCategoryForAll,
		Move:           2,
	},
	{
		Id:             158,
		Level:          1,
		MaxLevel:       0,
		Exp:            0,
		Name:           "绝影",
		UnitCategoryId: c2unit_category.UnitCategoryForAll,
		Move:           1,
	},
	{
		Id:             159,
		Level:          1,
		MaxLevel:       0,
		Exp:            0,
		Name:           "赤兔马",
		UnitCategoryId: c2unit_category.UnitCategoryForAll,
		// 突击移动：在获得移动范围时处理
	},
	{
		Id:             160,
		Level:          1,
		MaxLevel:       0,
		Exp:            0,
		Name:           "的卢",
		UnitCategoryId: c2unit_category.UnitCategoryForAll,
		// 恶路移动：在获得移动范围时处理
	},
	{
		Id:             161,
		Level:          1,
		MaxLevel:       0,
		Exp:            0,
		Name:           "铁盔",
		UnitCategoryId: c2unit_category.UnitCategoryWuJiang,
		BaseHPInc:      45,
	},
	{
		Id:             162,
		Level:          1,
		MaxLevel:       0,
		Exp:            0,
		Name:           "诸葛巾",
		UnitCategoryId: c2unit_category.UnitCategoryWuJiang,
		BaseMPInc:      45,
	},
	{
		Id:             163,
		Level:          1,
		MaxLevel:       0,
		Exp:            0,
		Name:           "没羽剑",
		UnitCategoryId: c2unit_category.UnitCategoryForSword, // 不知道是不是
		AttackRange:    c2unit_category.AttackRange10,
	},
	{
		Id:             164,
		Level:          1,
		MaxLevel:       0,
		Exp:            0,
		Name:           "孙子兵法",
		UnitCategoryId: c2unit_category.UnitCategoryForAll,
		BaseExpInc:     4,
	},
	{
		Id:                    165,
		Level:                 1,
		MaxLevel:              0,
		Exp:                   0,
		Name:                  "孟德新书",
		UnitCategoryId:        c2unit_category.UnitCategoryForAll,
		BaseExpIncRatio:       50,
		BaseWeaponExpIncRatio: 50,
		BaseArmorExpIncRatio:  50,
	},
	{
		Id:                 166,
		Level:              1,
		MaxLevel:           0,
		Exp:                0,
		Name:               "青囊书",
		UnitCategoryId:     c2unit_category.UnitCategoryForAll,
		BaseHPRecoverRatio: 10,
	},
	{
		Id:             167,
		Level:          1,
		MaxLevel:       0,
		Exp:            0,
		Name:           "太平清领道",
		UnitCategoryId: c2unit_category.UnitCategoryForAll,
		UnitStatus:     c2status.UnitStatusAllException,
	},
	{
		Id:                 168,
		Level:              1,
		MaxLevel:           0,
		Exp:                0,
		Name:               "太平要术",
		UnitCategoryId:     c2unit_category.UnitCategoryForAll,
		BaseMPRecoverRatio: 10,
	},
	{
		Id:             169,
		Level:          1,
		MaxLevel:       0,
		Exp:            0,
		Name:           "遁甲天书",
		UnitCategoryId: c2unit_category.UnitCategoryWenGuan,
		// 策略模仿：在获得策略列表时处理
	},
	{
		Id:               170,
		Level:            1,
		MaxLevel:         0,
		Exp:              0,
		Name:             "六韬",
		UnitCategoryId:   c2unit_category.UnitCategoryForAll,
		BaseWeaponExpInc: 4,
	},
	{
		Id:              171,
		Level:           1,
		MaxLevel:        0,
		Exp:             0,
		Name:            "三略",
		UnitCategoryId:  c2unit_category.UnitCategoryForAll,
		BaseArmorExpInc: 4,
	},
	{
		Id:             172,
		Level:          1,
		MaxLevel:       0,
		Exp:            0,
		Name:           "豆袋",
		UnitCategoryId: c2unit_category.UnitCategoryForAll,
		// 自动使用豆：在攻击动作中处理
	},
	{
		Id:                       173,
		Level:                    1,
		MaxLevel:                 0,
		Exp:                      0,
		Name:                     "玉玺",
		UnitCategoryId:           c2unit_category.UnitCategoryForAll,
		BaseCriticalStrikeChance: 100,
	},
	{
		Id:             174,
		Level:          1,
		MaxLevel:       0,
		Exp:            0,
		Name:           "青龙宝玉",
		UnitCategoryId: c2unit_category.UnitCategoryQiMaCeShi,
	},
	{
		Id:             175,
		Level:          1,
		MaxLevel:       0,
		Exp:            0,
		Name:           "朱雀宝玉",
		UnitCategoryId: c2unit_category.UnitCategoryCeShi,
	},
	{
		Id:             176,
		Level:          1,
		MaxLevel:       0,
		Exp:            0,
		Name:           "玄武宝玉",
		UnitCategoryId: c2unit_category.UnitCategoryDaoShi,
	},
	{
		Id:             174,
		Level:          1,
		MaxLevel:       0,
		Exp:            0,
		Name:           "白虎宝玉",
		UnitCategoryId: c2unit_category.UnitCategoryFengShuiShi,
	},
}
